name: Update GitHub Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
permissions:
  contents: write  # 确保有写入权限
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - name: Generate JSON
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          python github_calendar.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add github_contributions_GWan1234.json
          git commit -m "update contributions" || true
          git push