name: clonetest
on:
  # kick off the job on demand
  workflow_dispatch:
  # and run on a schedule every 12 hours
  schedule:
    - cron: "* */12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: GWan1234/gha-clone-releases
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          src_repo: ophub/amlogic-s9xxx-armbian
          limit: 20