name: Delete All Releases (DANGEROUS)

on: workflow_dispatch

permissions:
  contents: write
  deployments: write
  actions: write

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete releases
        uses: sgpublic/delete-release-action@v1.1
        with:
          # repo: '<owner>/<repoName>' # you can input a another repo here, defaults to current repo
          release-drop: true
          release-keep-count: -1
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 0
          delete_workflows: true
          workflows_keep_day: 0
          gh_token: ${{ secrets.MY_TOKEN }}

      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
