name: Delete All Releases (DANGEROUS)

on: workflow_dispatch

permissions:
  contents: write
  deployments: write
  actions: write

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Cleaner
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}