name: Delete All Releases (DANGEROUS)

on: workflow_dispatch

permissions:
  contents: write
  deployments: write
  actions: write

jobs:
  clean-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 0
          delete_workflows: true
          workflows_keep_day: 0
          gh_token: ${{ secrets.MY_TOKEN }}

      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Delete releases Tags
        uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
